spring.application.name=jwtDemo


spring.datasource.url=jdbc:mysql://localhost:3306/jwtdb
spring.datasource.username=root
spring.datasource.password=Smart#@70

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=KCNMSalWLClQkjUJYvtBJscaLkTIF88VhWBhWd6OtEm
app.jwt.expiration-ms=3600000

razorpay.key-id=rzp_test_ShH5hjcEgz4HqN
razorpay.key-secret=21AndasiMBcbWaB9LcHr94Ud
razorpay.currency=INR
